---
abstract: 'implementation of the Polybius square'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Polybius
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Crypt::Polybius:
    file: lib/Crypt/Polybius.pm
    version: 0.001
requires:
  Moo: 1.002000
  Text::Unidecode: 0
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Crypt-Polybius/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Crypt-Polybius
  homepage: https://metacpan.org/release/Crypt-Polybius
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-crypt-polybius.git
version: 0.001
